# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consul_service_name', models.CharField(max_length=64)),
                ('service_site_name', models.CharField(max_length=64, unique=True)),
                ('plan_service_nodes', models.CharField(max_length=256)),
                ('ng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngapp.ng')),
            ],
        ),
    ]
