# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngapp', '0002_upstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstream',
            name='plan_service_nodes',
            field=models.TextField(),
        ),
    ]
