# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngapp', '0003_auto_20171122_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upstream',
            name='service_site_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='upstream',
            unique_together=set([('ng', 'service_site_name')]),
        ),
    ]
